config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  
# 名前付きのルーティングを定義することができる
  get "/help", to: "static_pages#help"
# help_path -> '/'
# help_url  -> 'https://www.example.com/help'
# 上の2つも使用できる
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  # /users/1といったユーザー情報を表示するURLの追加
  # さらにshow, new, edit, updateなどのRESTfulなアクションの追加
  resources :users do
  # GET	/users	index	users_path	すべてのユーザーを一覧するページ
  # GET	/users/1	show	user_path(user)	特定のユーザーを表示するページ
  # GET	/users/new	new	new_user_path	ユーザーを新規作成するページ（ユーザー登録）
  # POST	/users	create	users_path	ユーザーを作成するアクション
  # GET	/users/1/edit	edit	edit_user_path(user)	id=1のユーザーを編集するページ
  # PATCH	/users/1	update	user_path(user)	ユーザーを更新するアクション
  # DELETE	/users/1	destroy	user_path(user)	ユーザーを削除するアクション
    member do # memberを使うとユーザーidを含むURLを扱うようになる
      get :following, :followers
    end
  # GET	/users/1/following	following	following_user_path(1)
  # GET	/users/1/followers	followers	followers_user_path(1)
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  
  get '/microposts', to: 'static_pages#home'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_signingup.html.erb
<div class="center jumbotron">
    <h1>Welcome to the Sample App</h1>

    <h2>
      This is the home page for the
      <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
      sample application.
    </h2>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    
  </div>

app/views/static_pages/about.html.erb
<% provide(:title, "About")%>
<h1>About</h1>
<p>
  <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
  is a <a href="https://railstutorial.jp/#ebook">book</a> and
  <a href="https://railstutorial.jp/screencast">screencast</a>
  to teach web development with
  <a href="https://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample app for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title,"Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://railstutorial.jp/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help")%>
<hi>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="https://railstutorial.jp/help">Rails Tutorial Help page</a>
  To get help on this sample app, see the
  <a href="https://railstutorial.jp/#ebook"><em>Ruby on Rails Tutorial</em>
  book</a>
</p>
  

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <%= render 'shared/posting' %>
<% else %>
  <%= render 'signingup' %>
  <%= link_to image_tag("rails.svg", alt: "Rails logo", width: "200px"),
              "https://rubyonrails.org/" %>
<% end %>