config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  
# 名前付きのルーティングを定義することができる
  get "/help", to: "static_pages#help"
# help_path -> '/'
# help_url  -> 'https://www.example.com/help'
# 上の2つも使用できる
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  # /users/1といったユーザー情報を表示するURLの追加
  # さらにshow, new, edit, updateなどのRESTfulなアクションの追加
  resources :users do
  # GET	/users	index	users_path	すべてのユーザーを一覧するページ
  # GET	/users/1	show	user_path(user)	特定のユーザーを表示するページ
  # GET	/users/new	new	new_user_path	ユーザーを新規作成するページ（ユーザー登録）
  # POST	/users	create	users_path	ユーザーを作成するアクション
  # GET	/users/1/edit	edit	edit_user_path(user)	id=1のユーザーを編集するページ
  # PATCH	/users/1	update	user_path(user)	ユーザーを更新するアクション
  # DELETE	/users/1	destroy	user_path(user)	ユーザーを削除するアクション
    member do # memberを使うとユーザーidを含むURLを扱うようになる
      get :following, :followers
    end
  # GET	/users/1/following	following	following_user_path(1)
  # GET	/users/1/followers	followers	followers_user_path(1)
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  
  get '/microposts', to: 'static_pages#home'

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user, only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update] # 

  def new
  end

  def create # パスワードの再設定
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user # user見つけた場合
      @user.create_reset_digest # digestつくって
      @user.send_password_reset_email # 作ったtokenのURlが記載されているメールを送る
      flash[:info] = "Email sent password reset instructions"
      redirect_to root_url
    else
      flash.now[:danger] = "Email address not found"
      render 'new', status: :unprocessable_entity
    end
  end

  def edit

  end

  def update
    if params[:user][:password].empty? # passwordがからの時にerrorを追加する
      @user.errors.add(:password, "can't be empty")
      render 'edit',  status: :unprocessable_entity
    elsif @user.update(user_params) # 新しいpasswordが正しかったら更新
      reset_session
      log_in @user
      @user.update_attribute(:reset_digest, nil) # 使用後にreset_digestをnilにすることで次に同じページから再設定することを防ぐ
      flash[:success] = "Password has been reset."
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity # 失敗させ元の画面へ
    end
  end


  private

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    def get_user
      @user = User.find_by(email: params[:email])
    end

    def valid_user
      unless (@user && @user.activated? && @user.authenticated?(:reset, params[:id]))
        redirect_to root_url
      end
    end

    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "Password reset has expired."
        redirect_to new_password_reset_url
      end
    end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, 'Reset password') %>
<h1>Reset password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, url: password_reset_path(params[:id])) do |f| %>
        <%= render 'shared/error_messages', object: f.object%>

        <%= hidden_field_tag :email, @user.email %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Update password", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "Forgot password") %>
<h1>Forgot password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(url: password_resets_path, scope: :password_reset) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>